language: python
python:
 - "3.3"
 - "3.2"
 - "2.7"
install: "pip install -r requirements.txt"
script: nosetests
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python3-numpy